/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-07-12 14:42:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1657586304000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1656294610000L));
    _jspx_dependants.put("jar:file:/C:/8_FinalProject_workspace/HomeArtAll/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("  <title>Product example · Bootstrap v5.2</title>\n");
      out.write("  <style>\n");
      out.write("    /* 폰트 */\n");
      out.write("    @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;400&display=swap');\n");
      out.write("\n");
      out.write("    * {\n");
      out.write("      font-family: 'Noto Sans KR', sans-serif;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* banner */\n");
      out.write("    img {\n");
      out.write("      object-fit: cover;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .carousel-item>img {\n");
      out.write("      width: 100%;\n");
      out.write("      height: 600px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* content */\n");
      out.write("    .content {\n");
      out.write("      max-width: 1500px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #purchase-list {\n");
      out.write("      width: 1300px;\n");
      out.write("      overflow: hidden;\n");
      out.write("      padding: 10px 0;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #purchase-list ul {\n");
      out.write("      transition: transform 1.2s cubic-bezier(0.41, 1.29, 0.4, 1.3);\n");
      out.write("      background-color: transparent;\n");
      out.write("      box-shadow: none;\n");
      out.write("      margin: 0;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #purchase-list ul:nth-of-type(1) {\n");
      out.write("      margin-bottom: 20px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .purchase {\n");
      out.write("      min-width: 270px;\n");
      out.write("      height: 100px;\n");
      out.write("      border-radius: 7px;\n");
      out.write("      overflow: hidden;\n");
      out.write("      margin: 0 27px;\n");
      out.write("      transition: transform 0.07s linear;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .purchase:hover {\n");
      out.write("      transform: scale(1.1);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .purchase img {\n");
      out.write("      display: block;\n");
      out.write("      width: 100%\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    @keyframes shake-ani {\n");
      out.write("      0% {\n");
      out.write("        transform: translateX(0);\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      50% {\n");
      out.write("        transform: translateX(-6px);\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      100% {\n");
      out.write("        transform: translateX(6px);\n");
      out.write("      }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .shake {\n");
      out.write("      animation: shake-ani 0.1s linear alternate;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #expert-category {\n");
      out.write("      width: 100%;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #expert-category img {\n");
      out.write("      -webkit-mask-image: url(#mask-circle);\n");
      out.write("      mask-image: url(#mask-circle);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #expert-category .picture-area {\n");
      out.write("      background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/expert1.jpg);\n");
      out.write("      background-size: cover;\n");
      out.write("      background-position: center;\n");
      out.write("      background-repeat: no-repeat;\n");
      out.write("\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #expert-search input {\n");
      out.write("      border: none;\n");
      out.write("      outline: none;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #expert-search:hover {\n");
      out.write("      box-shadow: 0px 0px 20px #ced4da;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #purchase-slide>svg {\n");
      out.write("      transform: scale(1.5);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #today-pick {\n");
      out.write("      padding-top: 100px;\n");
      out.write("      height: 700px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #today-pick ul.today-pick-ani {\n");
      out.write("      transition: transform 0.7s cubic-bezier(0.18, 1.03, 0.18, 1.1);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #today-pick ul li {\n");
      out.write("      min-width: 448px;\n");
      out.write("      height: 500px;\n");
      out.write("      margin-right: 500px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .card {\n");
      out.write("      height: 100%;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #best-home .card {\n");
      out.write("      width: 480px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #best-home>div {\n");
      out.write("      margin-bottom: 50px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #today-list {\n");
      out.write("      width: 100%;\n");
      out.write("      z-index: 1;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #today-list>#box {\n");
      out.write("      max-height: 1644px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #today-list.Ymove-ani {\n");
      out.write("      transition: all 0.5s cubic-bezier(0.18, 1.03, 0.18, 1.1);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #expert-category,\n");
      out.write("    #search,\n");
      out.write("    #purchase-slide,\n");
      out.write("    #today-pick {\n");
      out.write("      position: relative;\n");
      out.write("      z-index: 5;\n");
      out.write("      background: white;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #today-list .card {\n");
      out.write("      width: 448px;\n");
      out.write("      height: 500px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #today-list .card img {\n");
      out.write("      height: 70%;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #up-and-down svg {\n");
      out.write("      margin-left: 20px;\n");
      out.write("      margin-right: 20px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #youtube {\n");
      out.write("      padding: 80px 0;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #youtube ul.Ymove {\n");
      out.write("      transition: all 1s cubic-bezier(0.18, 1.03, 0.18, 1.1);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #aaa:hover {\n");
      out.write("      fill: red;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #youtube>div:nth-of-type(3) svg:hover {\n");
      out.write("      fill: #4f8cd1;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #youtube ul li {\n");
      out.write("      width: 100%;\n");
      out.write("      height: 200px;\n");
      out.write("      margin-bottom: 50px;\n");
      out.write("      background: white;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .card-ani {\n");
      out.write("      box-shadow: rgb(100 111 124 / 20%) 0px 2px 8px;\n");
      out.write("      transition: all 0.2s linear;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .card-ani:hover {\n");
      out.write("      transform: scale(1.05);\n");
      out.write("      border: 1px solid #4f8cd1;\n");
      out.write("      box-shadow: #4f8cd1 0px 0px 3px 0px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .modal {\n");
      out.write("      position: absolute;\n");
      out.write("      top: 50%;\n");
      out.write("      left: 50%;\n");
      out.write("      transform: translate(-50%, -50%);\n");
      out.write("      width: 50px;\n");
      out.write("      height: 50px;\n");
      out.write("      border: 1px solid red;\n");
      out.write("      z-index: 1024;\n");
      out.write("      background-color: red;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .wrap {\n");
      out.write("      background: white;\n");
      out.write("      position: relative;\n");
      out.write("      z-index: 10;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #today-list .card {\n");
      out.write("      margin-right: 26px;\n");
      out.write("      margin-left: 26px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #loginModal {\n");
      out.write("      background-color: white;\n");
      out.write("      position: fixed;\n");
      out.write("      top: 50%;\n");
      out.write("      left: 50%;\n");
      out.write("      transform: translate(-50%, -50%);\n");
      out.write("      z-index: 100;\n");
      out.write("      width: 1000px;\n");
      out.write("      display: flex;\n");
      out.write("      box-shadow: 0px 0px 20px #e1e1e1;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #loginModal .member {\n");
      out.write("      width: 50%;\n");
      out.write("    }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write(" ");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("  <div id=\"carouselExampleFade\" class=\"banner carousel slide carousel-fade\" data-bs-ride=\"carousel\">\n");
      out.write("    <div class=\"carousel-inner\">\n");
      out.write("      <div class=\"carousel-item active\">\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/banner1.jpg.png\" class=\"d-block w-100\" alt=\"...\">\n");
      out.write("      </div>\n");
      out.write("      <div class=\"carousel-item\">\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/banner2.jpg.png\" class=\"d-block w-100\" alt=\"...\">\n");
      out.write("      </div>\n");
      out.write("      <div class=\"carousel-item\">\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/banner3.jpg.png\" class=\"d-block w-100\" alt=\"...\">\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselExampleFade\" data-bs-slide=\"prev\">\n");
      out.write("      <svg width=\"50px\" height=\"50px\" xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='black'>\n");
      out.write("        <path d='M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z' />\n");
      out.write("      </svg>\n");
      out.write("      <span class=\"visually-hidden\">Previous</span>\n");
      out.write("    </button>\n");
      out.write("    <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselExampleFade\" data-bs-slide=\"next\">\n");
      out.write("      <svg width=\"50px\" height=\"50px\" xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='black'>\n");
      out.write("        <path d='M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z' />\n");
      out.write("      </svg>\n");
      out.write("      <span class=\"visually-hidden\">Next</span>\n");
      out.write("    </button>\n");
      out.write("  </div>\n");
      out.write("  <div class=\"content mx-auto mb-5 position-relative\">\n");
      out.write("\n");
      out.write("    <div class=\"wrap\">\n");
      out.write("      <!-- expert, product guide -->\n");
      out.write("      <div id=\"expert-category\" class=\"row py-5 my-5\">\n");
      out.write("        <div class=\"col-md-7 d-flex justify-content-center align-items-center p-0\">\n");
      out.write("          <div class=\"text-center\">\n");
      out.write("            <h1 style=\"font-size: 3.5rem\">필요한 정보를 검색하세요.</h1>\n");
      out.write("            <br>\n");
      out.write("            <p class=\"fs-3\">\n");
      out.write("              HomeArt에는 홈 인테리어에 도움이 되는 수많은 정보들이 있습니다.<br />\n");
      out.write("              상품 혹은 전문가 등을 검색하여 당신의 집을 아름답게 꾸며보세요.\n");
      out.write("            </p>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"picture-area col-md-5 position-relative p-0 d-flex\" style=\"height: 500px;\">\n");
      out.write("          <svg xmlns=\"http://www.w3.org/2000/svg\" class=\"position-absolute top-0 start-0 w-100 h-100\">\n");
      out.write("            <defs>\n");
      out.write("              <mask id=\"mask-circle\">\n");
      out.write("                <rect x=\"0\" y=\"0\" width=\"100%\" height=\"100%\" fill=\"white\"></rect>\n");
      out.write("\n");
      out.write("                <svg id=\"sw-js-blob-svg\" viewBox=\"0 0 100 100\" xmlns=\"http://www.w3.org/2000/svg\" version=\"1.1\">\n");
      out.write("                  <path\n");
      out.write("                    d=\"M22.3,-38.9C29,-34.7,34.6,-29,36.4,-22.2C38.2,-15.5,36.1,-7.8,35,-0.6C33.9,6.5,33.9,13,32.1,19.7C30.3,26.4,26.7,33.2,21.1,38.1C15.4,43,7.7,46,0.6,45C-6.6,44,-13.1,39,-19.5,34.6C-25.9,30.1,-32.1,26.1,-36.6,20.4C-41.1,14.8,-43.9,7.4,-43.3,0.4C-42.6,-6.7,-38.6,-13.3,-34.1,-19C-29.6,-24.6,-24.6,-29.3,-18.8,-34C-13.1,-38.7,-6.5,-43.4,0.6,-44.5C7.8,-45.6,15.6,-43,22.3,-38.9Z\"\n");
      out.write("                    width=\"100%\" height=\"100%\" transform=\"translate(50 50)\" stroke-width=\"0\" style=\"transition: all 0.3s ease 0s; fill: black;\"></path>\n");
      out.write("                </svg>\n");
      out.write("              </mask>\n");
      out.write("            </defs>\n");
      out.write("            <g mask=\"url(#mask-circle)\">\n");
      out.write("              <rect x=\"0\" y=\"0\" width=\"100%\" height=\"100%\" fill=\"white\"></rect>\n");
      out.write("            </g>\n");
      out.write("          </svg>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <!-- expert, product search -->\n");
      out.write("      <div id=\"search\" class=\"d-flex justify-content-center align-items-center py-5 mt-5\">\n");
      out.write("        <svg width=\"25\" height=\"25\" class=\"position-relative\" style=\"left: 40px;\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\">\n");
      out.write("          <!--! Font Awesome Pro 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. -->\n");
      out.write("          <path\n");
      out.write("            d=\"M500.3 443.7l-119.7-119.7c27.22-40.41 40.65-90.9 33.46-144.7C401.8 87.79 326.8 13.32 235.2 1.723C99.01-15.51-15.51 99.01 1.724 235.2c11.6 91.64 86.08 166.7 177.6 178.9c53.8 7.189 104.3-6.236 144.7-33.46l119.7 119.7c15.62 15.62 40.95 15.62 56.57 0C515.9 484.7 515.9 459.3 500.3 443.7zM79.1 208c0-70.58 57.42-128 128-128s128 57.42 128 128c0 70.58-57.42 128-128 128S79.1 278.6 79.1 208z\" />\n");
      out.write("        </svg>\n");
      out.write("        <div id=\"expert-search\" style=\"width: 600px;\" class=\"form-control p-0 rounded-pill\">\n");
      out.write("          <input style=\"font-size: 18px; width: 550px\" type=\"text\" class=\"float-end py-2 pe-4 rounded-pill\" />\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div id=\"test\" class=\"row my-5\">\n");
      out.write("        <div class=\"col-md-6 d-flex justify-content-center align-items-center\" style=\"background-color\">\n");
      out.write("          <div class=\"text-center\">\n");
      out.write("            <h1 style=\"font-size: 3.5rem\">Home Story</h1>\n");
      out.write("            <br>\n");
      out.write("            <p class=\"fs-3\" style=\"\">\n");
      out.write("              당신의 인테리어 이야기를 모두와 공유해보세요. <br />\n");
      out.write("              아직 갈피를 못 찾았다면, 훌륭한 이야기를 참고할 수도 있죠.\n");
      out.write("            </p>\n");
      out.write("            <input type=\"checkbox\" class=\"btn-check\" id=\"allview-check2\" autocomplete=\"off\">\n");
      out.write("            <label onclick=\"location.href='communityList.bo'\" class=\"btn btn-outline-primary rounded-pill fs-4 p-3\" for=\"allview-check2\" style=\"width: 400px;\">\n");
      out.write("              전체 보기\n");
      out.write("            </label>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-6 position-relative p-0\">\n");
      out.write("          <img class=\"position-absolute top-0 start-0 w-100 h-100\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/go-top9.jpg\" alt=\"\">\n");
      out.write("          <svg class=\"position-relative\" id=\"sw-js-blob-svg\" viewBox=\"0 0 100 100\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("            <defs>\n");
      out.write("              <mask id=\"mask-top9\">\n");
      out.write("                <rect mask=\"url(#mask-top9)\" x=\"0\" y=\"0\" class=\"w-100 h-100\" fill=\"white\"></rect>\n");
      out.write("                <path fill=\"black\" d=\"M21.4,-38C26.4,-34.1,28.4,-25.8,29.8,-18.7C31.2,-11.7,32,-5.8,33.9,1.1C35.8,8,38.8,16.1,37,22.6C35.3,29.1,28.9,34.1,22,35.5C15,37,7.5,34.9,-0.1,35C-7.7,35.1,-15.3,37.4,-20.2,34.8C-25.1,32.2,-27.3,24.6,-30.7,18C-34.1,11.3,-38.8,5.7,-39.7,-0.5C-40.5,-6.7,-37.5,-13.3,-33,-18C-28.5,-22.7,-22.4,-25.4,-16.6,-29C-10.8,-32.5,-5.4,-36.8,1.4,-39.2C8.2,-41.5,16.3,-42,21.4,-38Z\"\n");
      out.write("                  width=\"100%\" height=\"100%\" transform=\"translate(50 50)\" stroke-width=\"0\" style=\"transition: all 0.3s ease 0s;\">\n");
      out.write("                </path>\n");
      out.write("              </mask>\n");
      out.write("            </defs>\n");
      out.write("            <rect mask=\"url(#mask-top9)\" x=\"0\" y=\"0\" class=\"w-100 h-100\" fill=\"white\"></rect>\n");
      out.write("            <text x=\"50%\" y=\"50%\"  text-anchor=\"middle\" dominant-baseline=\"central\" fill=\"white\">Top-9</text>\n");
      out.write("          </svg>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div id=\"best-home\" class=\"mb-5\">\n");
      out.write("        <div class=\"d-flex flex-wrap\">\n");
      out.write("        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("      </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <!-- today pick silde -->\n");
      out.write("      <div id=\"today-pick\" class=\"row d-flex justify-content-center\">\n");
      out.write("        <div class=\"col-md-5 d-flex justify-content-center align-items-center\">\n");
      out.write("          <div class=\"overflow-hidden\" style=\"width: 28rem; height: 500px;\">\n");
      out.write("            <ul class=\"list-unstyled d-flex p-0 today-pick-ani\">\n");
      out.write("               ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-7 d-flex justify-content-center align-items-center\">\n");
      out.write("          <div class=\"text-center\">\n");
      out.write("            <h1 style=\"font-size: 3.5rem\">today's pick</h1>\n");
      out.write("            <br>\n");
      out.write("            <p class=\"fs-3\">\n");
      out.write("              당신을 위해, 새로운 상품들을 준비했습니다. <br />\n");
      out.write("              어딘가에는 당신의 방에 딱 어울리는 가구가 있을지도 몰라요!\n");
      out.write("            </p>\n");
      out.write("            <input type=\"checkbox\" class=\"btn-check\" id=\"allview-check\" autocomplete=\"off\">\n");
      out.write("            <label onclick=\"location.href='glist.go'\" class=\"btn btn-outline-primary rounded-pill fs-4 p-3\" for=\"allview-check\" style=\"width: 400px;\">바로가기</label>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("  </div>\n");
      out.write("  <div style=\"height: 270px;\" class=\"position-relative\">\n");
      out.write("    <video class=\"w-100 h-100\" autoplay playsinline muted loop preload>\n");
      out.write("      <source src=\"http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4\">\n");
      out.write("    </video>\n");
      out.write("    <svg class=\"position-absolute top-0 start-0 w-100 h-100\" style=\"font-size: 5rem;\">\n");
      out.write("      <defs>\n");
      out.write("        <mask id=\"mask-text\">\n");
      out.write("          <rect x=\"0\" y=\"0\" width=\"100%\" height=\"100%\" fill=\"white\"></rect>\n");
      out.write("          <text x=\"50%\" y=\"50%\" text-anchor=\"middle\" dominant-baseline=\"central\" fill=\"black\">꿀팁 TV</text>\n");
      out.write("        </mask>\n");
      out.write("      </defs>\n");
      out.write("      <rect mask=\"url(#mask-text)\" x=\"0\" y=\"0\" width=\"100%\" height=\"100%\" fill=\"white\"></rect>\n");
      out.write("    </svg>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <div style=\"background: rgb(238, 243, 250);\">\n");
      out.write("    <div id=\"youtube\" class=\"row mx-auto\" style=\"width: 1500px;\">\n");
      out.write("      <div class=\"text-start p-0\">\n");
      out.write("        <svg id=\"aaa\" width=\"72\" height=\"56\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 576 512\">\n");
      out.write("          <!--! Font Awesome Pro 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. -->\n");
      out.write("          <path\n");
      out.write("            d=\"M549.655 124.083c-6.281-23.65-24.787-42.276-48.284-48.597C458.781 64 288 64 288 64S117.22 64 74.629 75.486c-23.497 6.322-42.003 24.947-48.284 48.597-11.412 42.867-11.412 132.305-11.412 132.305s0 89.438 11.412 132.305c6.281 23.65 24.787 41.5 48.284 47.821C117.22 448 288 448 288 448s170.78 0 213.371-11.486c23.497-6.321 42.003-24.171 48.284-47.821 11.412-42.867 11.412-132.305 11.412-132.305s0-89.438-11.412-132.305zm-317.51 213.508V175.185l142.739 81.205-142.739 81.201z\" />\n");
      out.write("        </svg>\n");
      out.write("        유튜브 바로가기\n");
      out.write("      </div>\n");
      out.write("      <div class=\"col-md-7 p-0\">\n");
      out.write("        <iframe class=\"rounded\" width=\"100%\" height=\"100%\" src=\"https://www.youtube.com/embed/ZMYrfd0SPdc\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\"\n");
      out.write("          allowfullscreen></iframe>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"col-md-5 p-0 text-center\">\n");
      out.write("        <svg width=\"40\" height=\"60\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 384 512\">\n");
      out.write("          <!--! Font Awesome Pro 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. -->\n");
      out.write("          <path d=\"M352 352c-8.188 0-16.38-3.125-22.62-9.375L192 205.3l-137.4 137.4c-12.5 12.5-32.75 12.5-45.25 0s-12.5-32.75 0-45.25l160-160c12.5-12.5 32.75-12.5 45.25 0l160 160c12.5 12.5 12.5 32.75 0 45.25C368.4 348.9 360.2 352 352 352z\" />\n");
      out.write("        </svg>\n");
      out.write("        <div class=\"slide-wrap overflow-hidden py-3 px-4\" style=\"height: 736px;\">\n");
      out.write("          <ul class=\"list-unstyled h-100 p-0 m-0 position-relative Ymove\">\n");
      out.write("            <li class=\"rounded d-flex align-content-center p-3 card-ani\">\n");
      out.write("\n");
      out.write("              <div class=\"w-100 h-100 d-flex align-items-center\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                  <div class=\"col-md-6\">\n");
      out.write("                    <img class=\"w-100 h-100 rounded\" src=\"https://img.youtube.com/vi/jZ-5EQk8bQw/maxresdefault.jpg\" alt=\"\">\n");
      out.write("                    <span class=\"d-none\">jZ-5EQk8bQw</span>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"col-md-6\">\n");
      out.write("                    <h4>2평 학생방 꾸미기</h4>\n");
      out.write("                    <p>\n");
      out.write("                   		  집꾸미기 인테리어\n");
      out.write("                    </p>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"rounded d-flex align-content-center p-3 card-ani\">\n");
      out.write("\n");
      out.write("              <div class=\"w-100 h-100 d-flex align-items-center\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                  <div class=\"col-md-6\">\n");
      out.write("                    <img class=\"w-100 h-100 rounded\" src=\"https://img.youtube.com/vi/vIP-ecxf6DI/maxresdefault.jpg\" alt=\"\">\n");
      out.write("                    <span class=\"d-none\">vIP-ecxf6DI</span>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"col-md-6\">\n");
      out.write("                    <h4>33평 아파트 인테리어 거실 배치 꿀팀</h4>\n");
      out.write("                    <p>\n");
      out.write("                      		House Room Tour\n");
      out.write("                    </p>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            </li>\n");
      out.write("            <li class=\"rounded d-flex align-content-center p-3 card-ani\">\n");
      out.write("\n");
      out.write("              <div class=\"w-100 h-100 d-flex align-items-center\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                  <div class=\"col-md-6\">\n");
      out.write("                    <img class=\"w-100 h-100 rounded\" src=\"https://img.youtube.com/vi/nby0k5LwgU8/maxresdefault.jpg\" alt=\"\">\n");
      out.write("                    <span class=\"d-none\">nby0k5LwgU8</span>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"col-md-6\">\n");
      out.write("                    <h4>디자이너 부부의 요리 주방!</h4>\n");
      out.write("                    <p>\n");
      out.write("                         	주방 중심 인테리어\n");
      out.write("                    </p>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("            </li>\n");
      out.write("\n");
      out.write("            <li class=\"rounded d-flex align-content-center p-3 card-ani\">\n");
      out.write("\n");
      out.write("              <div class=\"w-100 h-100 d-flex align-items-center\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                  <div class=\"col-md-6\">\n");
      out.write("                    <img class=\"w-100 h-100 rounded\" src=\"https://img.youtube.com/vi/XlI3aeqGmQc/maxresdefault.jpg\" alt=\"\">\n");
      out.write("                    <span class=\"d-none\">XlI3aeqGmQc</span>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"col-md-6\">\n");
      out.write("                    <h4>테라스 + 다락방 탑층 인테리어</h4>\n");
      out.write("                    <p>\n");
      out.write("                      	힐링 테라스와 함께\n");
      out.write("                    </p>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("            </li>\n");
      out.write("          </ul>\n");
      out.write("        </div>\n");
      out.write("        <svg width=\"40\" height=\"60\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 384 512\">\n");
      out.write("          <!--! Font Awesome Pro 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. -->\n");
      out.write("          <path d=\"M192 384c-8.188 0-16.38-3.125-22.62-9.375l-160-160c-12.5-12.5-12.5-32.75 0-45.25s32.75-12.5 45.25 0L192 306.8l137.4-137.4c12.5-12.5 32.75-12.5 45.25 0s12.5 32.75 0 45.25l-160 160C208.4 380.9 200.2 384 192 384z\" />\n");
      out.write("        </svg>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"mx-auto\" style=\"max-width: 1500px; margin-top:300px;\">\r\n");
      out.write("    <footer class=\"row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 my-5 border-top\">\r\n");
      out.write("      <div class=\"col mb-3\">\r\n");
      out.write("        <a href=\"/\" class=\"d-flex align-items-center mb-3 link-dark text-decoration-none\">\r\n");
      out.write("          <img class=\"me-4\" style=\"width: 60px;\" src=\"images/로고.png\" alt=\"\">\r\n");
      out.write("        </a>\r\n");
      out.write("        <p class=\"text-muted\">&copy; 2022</p>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col mb-3\">\r\n");
      out.write("        <h5>about</h5>\r\n");
      out.write("        <ul class=\"nav flex-column\">\r\n");
      out.write("          <li class=\"nav-item mb-2\"><a href=\"#\" class=\"nav-link p-0 text-muted\">회사명:HomeArt</a></li>\r\n");
      out.write("          <li class=\"nav-item mb-2\"><a href=\"#\" class=\"nav-link p-0 text-muted\">대표:SinWoo Park</a></li>\r\n");
      out.write("          <li class=\"nav-item mb-2\"><a href=\"#\" class=\"nav-link p-0 text-muted\">전화번호:010-0000-0000</a></li>\r\n");
      out.write("          <li class=\"nav-item mb-2\"><a href=\"#\" class=\"nav-link p-0 text-muted\">사업자 번호:000-00-000</a></li>\r\n");
      out.write("          <li class=\"nav-item mb-2\"><a href=\"#\" class=\"nav-link p-0 text-muted\">주소:경기도 수원시 팔달구 월드컵로 321번길 신화빌딩 4층</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("      <div class=\"col mb-3\">\r\n");
      out.write("        <ul class=\"d-flex list-unstyled\">\r\n");
      out.write("          <li class=\"nav-item mb-2 mx-5\">\r\n");
      out.write("            <a href=\"#\" class=\"nav-link p-0 text-muted\">\r\n");
      out.write("              <svg fill=\"#6c757d\" width=\"64\" height=\"64\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\">\r\n");
      out.write("                <!--! Font Awesome Pro 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. -->\r\n");
      out.write("                <path\r\n");
      out.write("                  d=\"M504 256C504 119 393 8 256 8S8 119 8 256c0 123.78 90.69 226.38 209.25 245V327.69h-63V256h63v-54.64c0-62.15 37-96.48 93.67-96.48 27.14 0 55.52 4.84 55.52 4.84v61h-31.28c-30.8 0-40.41 19.12-40.41 38.73V256h68.78l-11 71.69h-57.78V501C413.31 482.38 504 379.78 504 256z\" />\r\n");
      out.write("              </svg>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item mb-2 mx-5\">\r\n");
      out.write("            <a href=\"#\" class=\"nav-link p-0 text-muted\">\r\n");
      out.write("              <svg fill=\"#6c757d\" width=\"64\" height=\"64\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\">\r\n");
      out.write("                <!--! Font Awesome Pro 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. -->\r\n");
      out.write("                <path\r\n");
      out.write("                  d=\"M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z\" />\r\n");
      out.write("              </svg>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item mb-2 mx-5\">\r\n");
      out.write("            <a href=\"https://www.instagram.com/____homeart/\" class=\"nav-link p-0 text-muted\">\r\n");
      out.write("              <svg fill=\"#6c757d\" width=\"64\" height=\"64\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 448 512\">\r\n");
      out.write("                <!--! Font Awesome Pro 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. -->\r\n");
      out.write("                <path\r\n");
      out.write("                  d=\"M224,202.66A53.34,53.34,0,1,0,277.36,256,53.38,53.38,0,0,0,224,202.66Zm124.71-41a54,54,0,0,0-30.41-30.41c-21-8.29-71-6.43-94.3-6.43s-73.25-1.93-94.31,6.43a54,54,0,0,0-30.41,30.41c-8.28,21-6.43,71.05-6.43,94.33S91,329.26,99.32,350.33a54,54,0,0,0,30.41,30.41c21,8.29,71,6.43,94.31,6.43s73.24,1.93,94.3-6.43a54,54,0,0,0,30.41-30.41c8.35-21,6.43-71.05,6.43-94.33S357.1,182.74,348.75,161.67ZM224,338a82,82,0,1,1,82-82A81.9,81.9,0,0,1,224,338Zm85.38-148.3a19.14,19.14,0,1,1,19.13-19.14A19.1,19.1,0,0,1,309.42,189.74ZM400,32H48A48,48,0,0,0,0,80V432a48,48,0,0,0,48,48H400a48,48,0,0,0,48-48V80A48,48,0,0,0,400,32ZM382.88,322c-1.29,25.63-7.14,48.34-25.85,67s-41.4,24.63-67,25.85c-26.41,1.49-105.59,1.49-132,0-25.63-1.29-48.26-7.15-67-25.85s-24.63-41.42-25.85-67c-1.49-26.42-1.49-105.61,0-132,1.29-25.63,7.07-48.34,25.85-67s41.47-24.56,67-25.78c26.41-1.49,105.59-1.49,132,0,25.63,1.29,48.33,7.15,67,25.85s24.63,41.42,25.85,67.05C384.37,216.44,384.37,295.56,382.88,322Z\" />\r\n");
      out.write("              </svg>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js\">\r\n");
      out.write("   </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("  <script src=\"https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.6.0.min.js\"></script>\n");
      out.write("  <script>\n");
      out.write("    var up = $('#youtube').find('svg').eq(1);\n");
      out.write("    var down = $('#youtube').find('svg').eq(2);\n");
      out.write("    var currentY = 0;\n");
      out.write("    var youtubeCurrentSlide = 1;\n");
      out.write("    var youtubeMaxSlide = $('#youtube ul li').length;\n");
      out.write("    //addClone($('#youtube ul li'));\n");
      out.write("    initialSlide();\n");
      out.write("\n");
      out.write("    $('#youtube ul li').on('click', function() {\n");
      out.write("      var name = $(this).find('span').eq(0).text();\n");
      out.write("      $('#youtube iframe').attr('src', \"https://www.youtube.com/embed/\" + name);\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    up.on('click', goUp);\n");
      out.write("\n");
      out.write("    function goUp() {\n");
      out.write("      if (!$('#youtube ul').hasClass('Ymove')) {\n");
      out.write("        $('#youtube ul').addClass('Ymove')\n");
      out.write("      }\n");
      out.write("      currentY = currentY - 250;\n");
      out.write("\n");
      out.write("      if (youtubeCurrentSlide === youtubeMaxSlide) {\n");
      out.write("        setTimeout(function() {\n");
      out.write("          $('#youtube ul').removeClass('Ymove');\n");
      out.write("          currentY = 0;\n");
      out.write("\n");
      out.write("          $('#youtube ul').css({\n");
      out.write("            'transform': 'translateY(' + currentY + 'px)'\n");
      out.write("          });\n");
      out.write("          youtubeCurrentSlide = 1;\n");
      out.write("        }, 1000);\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      $('#youtube ul').css({\n");
      out.write("        'transform': 'translateY(' + currentY + 'px)'\n");
      out.write("      });\n");
      out.write("      youtubeCurrentSlide++;\n");
      out.write("      console.log(youtubeCurrentSlide + \", \" + youtubeMaxSlide);\n");
      out.write("\n");
      out.write("      up.off('click'); //이벤트를 없애고\n");
      out.write("      setTimeout(function() {\n");
      out.write("        up.on('click', goUp);\n");
      out.write("      }, 1000);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    down.on('click', goDown);\n");
      out.write("\n");
      out.write("    function goDown() {\n");
      out.write("      console.log(youtubeCurrentSlide + \", \" + youtubeMaxSlide);\n");
      out.write("      if (!$('#youtube ul').hasClass('Ymove')) {\n");
      out.write("        $('#youtube ul').addClass('Ymove')\n");
      out.write("      }\n");
      out.write("      currentY = currentY + 250;\n");
      out.write("\n");
      out.write("      if (youtubeCurrentSlide === -(youtubeMaxSlide - 2)) {\n");
      out.write("        setTimeout(function() {\n");
      out.write("          $('#youtube ul').removeClass('Ymove');\n");
      out.write("          currentY = 0;\n");
      out.write("\n");
      out.write("          $('#youtube ul').css({\n");
      out.write("            'transform': 'translateY(' + currentY + 'px)'\n");
      out.write("          });\n");
      out.write("          youtubeCurrentSlide = 1;\n");
      out.write("        }, 1000);\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      $('#youtube ul').css({\n");
      out.write("        'transform': 'translateY(' + currentY + 'px)'\n");
      out.write("      });\n");
      out.write("      youtubeCurrentSlide--;\n");
      out.write("\n");
      out.write("      down.off('click'); //이벤트를 없애고\n");
      out.write("      setTimeout(function() {\n");
      out.write("        down.on('click', goDown);\n");
      out.write("      }, 1000);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function initialSlide() {\n");
      out.write("      var clone1 = $('#youtube ul li').clone(true);\n");
      out.write("      var clone2 = $('#youtube ul li').clone(true);\n");
      out.write("\n");
      out.write("      $('.slide-wrap ul').prepend(clone1.addClass('clone'));\n");
      out.write("      $('.slide-wrap ul').append(clone2.addClass('clone'));\n");
      out.write("\n");
      out.write("      $('.slide-wrap ul').css({\n");
      out.write("        'top': '-1000px'\n");
      out.write("      });\n");
      out.write("    }\n");
      out.write("  </script>\n");
      out.write("    \n");
      out.write("  <script>\n");
      out.write("  $('#expert-search input').on('focus', function() {\n");
      out.write("      $('#expert-search').css({\n");
      out.write("        'box-shadow': '0px 0px 5px #4f8cd1'\n");
      out.write("      });\n");
      out.write("      if(window.eventkeyCode === 13) {\n");
      out.write("        console.log('Wlrdma');\n");
      out.write("       }else{\n");
      out.write("          console.log('fsdfsdfsdf');\n");
      out.write("       }\n");
      out.write("    }).on('blur', function() {\n");
      out.write("      $('#expert-search').css({\n");
      out.write("        'box-shadow': 'none',\n");
      out.write("        'border': '1px solid #ced4da'\n");
      out.write("      });\n");
      out.write("    }).on('keypress', function(e){\n");
      out.write("       if(e.keyCode === 13) {\n");
      out.write("          location.href = 'search.se?title=' + $(this).val();\n");
      out.write("       }\n");
      out.write("    });\n");
      out.write("        </script>\n");
      out.write("  <script>\n");
      out.write("    var today_x = 0;\n");
      out.write("    var maxSlideCount = $('#today-pick ul li').length;\n");
      out.write("    var today_currentSlide = 1;\n");
      out.write("    var today_SlideMargin = 500;\n");
      out.write("    var today_SlideWidth = 448;\n");
      out.write("    var today_moveWidth = today_SlideMargin + today_SlideWidth;\n");
      out.write("    var ul = $('#today-pick ul');\n");
      out.write("\n");
      out.write("    makeClone(ul);\n");
      out.write("\n");
      out.write("    setInterval(todayMove, 3000);\n");
      out.write("\n");
      out.write("    function makeClone(tag) {\n");
      out.write("      tag.append(tag.children().first().clone(true));\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function moveTranslateX(tag, x) {\n");
      out.write("      tag.css({\n");
      out.write("        'transform': 'translateX(' + x + 'px)'\n");
      out.write("      });\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function todayMove() {\n");
      out.write("      if (!ul.hasClass('today-pick-ani')) {\n");
      out.write("        ul.addClass('today-pick-ani');\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      today_x = today_x - today_moveWidth;\n");
      out.write("\n");
      out.write("      if (today_currentSlide === maxSlideCount) {\n");
      out.write("        setTimeout(function() {\n");
      out.write("          ul.removeClass('today-pick-ani');\n");
      out.write("          today_x = 0;\n");
      out.write("          moveTranslateX(ul, today_x);\n");
      out.write("        }, 700);\n");
      out.write("\n");
      out.write("        today_currentSlide = 0;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      moveTranslateX(ul, today_x);\n");
      out.write("\n");
      out.write("      today_currentSlide = today_currentSlide + 1;\n");
      out.write("    }\n");
      out.write("  </script>\n");
      out.write("  <script>\n");
      out.write("    var x = 0;\n");
      out.write("    var maxSlide = $(\".purchase\").length / 8;\n");
      out.write("    var currentSlide = 1;\n");
      out.write("\n");
      out.write("    if (!Number.isInteger(maxSlide)) {\n");
      out.write("      maxSlide = parseInt(maxSlide) + 1;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    $(\"#go_left\").on('click', function() {\n");
      out.write("      console.log(\"left : \" + currentSlide);\n");
      out.write("      if (currentSlide > 1) {\n");
      out.write("        currentSlide = currentSlide - 1;\n");
      out.write("        x = x + 1000;\n");
      out.write("        console.log(\"x : \" + x);\n");
      out.write("        $(\"#purchase-list ul\").css({\n");
      out.write("          'transform': 'translateX(' + x + 'px)'\n");
      out.write("        });\n");
      out.write("      } else {\n");
      out.write("        $(\"#go_left\").removeClass('shake');\n");
      out.write("        $(\"#go_left\").offset().left;\n");
      out.write("        $(\"#go_left\").addClass('shake');\n");
      out.write("      }\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    $(\"#go_right\").on('click', function() {\n");
      out.write("      console.log(\"right : \" + currentSlide);\n");
      out.write("      if (currentSlide < maxSlide) {\n");
      out.write("        currentSlide = currentSlide + 1;\n");
      out.write("        x = x - 1000;\n");
      out.write("        console.log(\"x : \" + x);\n");
      out.write("        $(\"#purchase-list ul\").css({\n");
      out.write("          'transform': 'translateX(' + x + 'px)'\n");
      out.write("        });\n");
      out.write("      } else {\n");
      out.write("        $(\"#go_right\").removeClass('shake');\n");
      out.write("        $(\"#go_right\").offset().left;\n");
      out.write("        $(\"#go_right\").addClass('shake');\n");
      out.write("      }\n");
      out.write("    });\n");
      out.write("  </script>\n");
      out.write("  <script>\n");
      out.write("  $(function(){\n");
      out.write("    $(\"ul a\").on(\"click\", function() {\n");
      out.write("      var position = $(this).parent().position();\n");
      out.write("      console.log($(this).parent());\n");
      out.write("      var width = $(this).parent().width();\n");
      out.write("\n");
      out.write("      $(\"ul .slide1\").css({\n");
      out.write("        opacity: 1,\n");
      out.write("        left: +position.left,\n");
      out.write("        width: width\n");
      out.write("      });\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    $(\"header ul a\").on(\"mouseover\", function() {\n");
      out.write("      var position = $(this).parent().position();\n");
      out.write("      var width = $(this).parent().width();\n");
      out.write("      $(\"header ul .slide2\").css({\n");
      out.write("        opacity: 1,\n");
      out.write("        left: +position.left,\n");
      out.write("        width: width\n");
      out.write("      }).addClass(\"squeeze\");\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    $(\"header ul a\").on(\"mouseout\", function() {\n");
      out.write("      $(\"ul .slide2\").css({\n");
      out.write("        opacity: 0\n");
      out.write("      }).removeClass(\"squeeze\");\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    var currentWidth = $(\"header ul\").find(\"li:nth-of-type(3) a\").parent(\"li\").width();\n");
      out.write("    var current = $(\"header ul li:nth-of-type(3) a\").position();\n");
      out.write("    console.log(\"currentWidth  : \" + currentWidth);\n");
      out.write("    console.log(\"current.left : \" + current.left);\n");
      out.write("    $(\"header .slide1\").css({\n");
      out.write("      'left': current.left,\n");
      out.write("      'width': currentWidth\n");
      out.write("    });\n");
      out.write("  })\n");
      out.write("  </script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /WEB-INF/views/home.jsp(256,1) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("common/menubar.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/home.jsp(364,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/home.jsp(364,8) '${boardList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${boardList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/home.jsp(364,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("board");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("           <div class=\"card card-ani\" style=\"margin-left: 10px; margin-right: 10px;\">\n");
            out.write("            <img style=\"height: 350px;\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/buploadFiles/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.changeName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"card-img-top\" alt=\"...\">\n");
            out.write("            <div class=\"card-body\" style=\"height: 150px;\">\n");
            out.write("              <div class=\"d-flex align-items-center\">\n");
            out.write("                <div style=\"width: 50px; height: 50px;\" class=\"rounded-circle overflow-hidden\">\n");
            out.write("                   <img class=\"h-100 w-100\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/muploadFiles/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.profilePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"/>\n");
            out.write("                </div>\n");
            out.write("                <span class=\"fs-5 ms-3\">\n");
            out.write("                  ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.writer }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\n");
            out.write("                </span>\n");
            out.write("              </div>\n");
            out.write("              <p class=\"mb-0 fs-4 mt-3\">\n");
            out.write("                     ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.boardTitle }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\n");
            out.write("              </p>\n");
            out.write("            </div>\n");
            out.write("          </div>\n");
            out.write("        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/home.jsp(390,15) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/home.jsp(390,15) '${purchaseList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${purchaseList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/home.jsp(390,15) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("pc");
      // /WEB-INF/views/home.jsp(390,15) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVarStatus("v");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("               <li onclick=\"location.href='gdetail.go?gId=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${v.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("'\">\n");
            out.write("                   <div class=\"card\">\n");
            out.write("                     <div class=\"w-100 overflow-hidden\">\n");
            out.write("                         <img style=\"height: 350px;\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/buploadFiles/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pc.reNameFileName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"card-img-top card-ani\" alt=\"...\">\n");
            out.write("                     </div>\n");
            out.write("                  <div class=\"card-body\" style=\"height: 148px;\">\n");
            out.write("                    <div class=\"company fw-light mb-2\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pc.goodsCompay }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\n");
            out.write("                    <h5>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pc.goodsTitle }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h5>\n");
            out.write("                    <div>\n");
            out.write("                      <span class=\"fs-1 text-danger fw-bold me-3\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pc.goodsPrice }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("원</span>\n");
            out.write("                    </div>\n");
            out.write("                  </div>\n");
            out.write("                </div>\n");
            out.write("              </li>\n");
            out.write("               ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
